# Generated by Django 4.1.7 on 2023-03-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
    ]
